version: "3.7"

services:
  ganache-cli:
    container_name: ganache-cli
    image: trufflesuite/ganache-cli
    restart: unless-stopped
    ports:
      - 8545:8545

  mongodb:
    container_name: mongodb_server
    image: mongo
    volumes:
      - $HOME/docker/volumes/mongodb:/var/opt/mongodb
    restart: unless-stopped
    ports:
      - 27017:27017

  dev:
    container_name: ${APP_NAME:-erc1155-events}-dev
    image: ${REGISTRY_USERNAME:-rwajon}/${APP_NAME:-erc1155-events}:${TAG:-latest}
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: sh -c "./scripts/run.sh"
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - ganache-cli
      - mongodb

  test:
    container_name: ${APP_NAME:-erc1155-events}-test
    image: ${REGISTRY_USERNAME:-rwajon}/${APP_NAME:-erc1155-events}:${TAG:-latest}
    build:
      context: .
      target: test
      dockerfile: ./Dockerfile
    command: sh -c "./scripts/test.sh"
    volumes:
      - .:/app
    depends_on:
      - ganache-cli
      - mongodb

  prod:
    container_name: ${APP_NAME:-erc1155-events}-prod
    image: ${REGISTRY_USERNAME:-rwajon}/${APP_NAME:-erc1155-events}:${TAG:-latest}
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    volumes:
      - .:/app
    restart: unless-stopped
